swagger: '2.0'
info:
  title: Regulator API
  description: API specification for OPERANDO's Regulator API
  version: "0.0.1"
host: localhost
schemes:
  - https
basePath: /regulator
produces:
  - application/json
################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  service-ticket:
    name: service ticket
    in: header
    required: true
    type: string
  regulation-body:
    name: regulation body
    in: body
    required: true
    schema:
      type: object
      properties:
        regulation:
          $ref: '#/definitions/PrivacyRegulationInput'
  reg-id:
    name: reg-id
    in: path
    description: the unique identifier of a regulation.
    type: string
    required: true
    
  osp-id:
    name: osp-id
    in: path
    description: the unique identifier of an online service provider
    type: string
    required: true


################################################################################
#                                 Responses                                    #
################################################################################
responses:
  unauthorised:
    description: The user is not authenticated with the OPERANDO system. Check that the service ticket provided by the authentication service is correctly included in the message body.
  forbidden:
    description: The user is authenticated with the OPERANDO system, but is not allowed to perform the requested action.

################################################################################
#                                   Paths                                      #
################################################################################
paths:
  /regulations:
    post:
      summary: Add a new regulation to the system.
      description: |
        Called by a regulator to ensure that the platform becomes compliant with the new regulation. The regulation that was saved is returned, along with an identifer which should be used to refer to it in later communication.
      parameters:
        - $ref: '#/parameters/service-ticket'
        - $ref: '#/parameters/regulation-body'
      tags:
        - regulations
      responses:
        201:
          description: The regulation was successfully created, and the platform has been made compliant with it.
          schema:
            $ref: '#/definitions/PrivacyRegulation'
        401:
          $ref: '#/responses/unauthorised'
        403:
          $ref: '#/responses/forbidden'
            
  /regulations/{reg-id}:
    put:
      summary: Update an exisiting regulation.
      description: |
        Called by a regulator to ensure that the platform becomes compliant with the new terms of the regulation. The regulation that was saved is returned, along with an identifer which should be used to refer to it in later communication.
      parameters:
        - $ref: '#/parameters/service-ticket'
        - $ref: '#/parameters/regulation-body'
        - $ref: '#/parameters/reg-id'
      tags:
        - regulations
      responses:
        204:
          description: The regulation was successfully updated, and the platform has been made compliant with it.
          schema:
            $ref: '#/definitions/PrivacyRegulationInput'
        401:
          $ref: '#/responses/unauthorised'
        403:
          $ref: '#/responses/forbidden'
            
  /osps/{osp-id}/compliance-report:
    get:
      summary: Get a report.
      description: |
        Called by a regulator to obtain a compliance report relating to the specified OSP.
      parameters:
        - $ref: '#/parameters/service-ticket'
        - $ref: '#/parameters/osp-id'
      tags:
        - reports
      responses:
        200:
          description: The request was successful. The report is returned in the response body in the requested format.
          schema:
            $ref: '#/definitions/ComplianceReport'
        401:
          $ref: '#/responses/unauthorised'
        403:
          $ref: '#/responses/forbidden'
          
################################################################################
#                              Object Definitions                             #
################################################################################   
definitions:
  PrivacyRegulationInput:
    $ref: "https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/PrivacyRegulationInput.yaml#/PrivacyRegulationInput"
  PrivacyRegulation:
    $ref: "https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/PrivacyRegulation.yaml#/PrivacyRegulation"
  ComplianceReport:
    $ref: "https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/ComplianceReport.yaml#/ComplianceReport"