swagger: '2.0'
info:
  title: eu.operando.core.udb
  description: | 
    Operando UDB module. The user accounts database; currently this
    only covers the privacy for benefit account information. User information
    and credentials will be intergrated with the chosen identity management
    server (used in Operando)
  version: "0.0.8"
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: localhost:8080
basePath: /operando/core/udb
schemes:
- http
- https
produces:
- application/json

################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: Users
    description: End users of the Privacy Service Provider.
    
################################################################################
#                                   Parameters                                 #
################################################################################
parameters:

  user-id:
    name: user-id
    in: path
    description: The user identifier number
    type: string
    required: true
    
################################################################################
#                                   PATHs                                      #
################################################################################
paths:
  /users/{user-id}/:
    get:
      summary: Read the user account information for the given user id.
      description: |
        Get the registered account information e.g. name, user type etc.
      tags:
        - Users
        - GET
      parameters:
        - $ref: '#/parameters/user-id'
      responses:
        '200':
          description: The UPP document requested to be read is returned in full
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/UserAccount.yaml#/UserAccount'
        '404':
          description: Error - the user does not exist.
    

    put:
      summary: Update user account entry in the database for the user.
      description: |
        Called when a user makes a change to their account information
      tags:
        - Users
        - PUT
      parameters:
        - $ref: '#/parameters/user-id'
          
        - name: upp
          in: body
          description: The changed instance of this user's account information
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/UserAccount.yaml#/UserAccount'
      responses:
        '204':
          description: The document (account info) was successfully updated in the database.
        '404':
          description: Error. No document exists to be updated.
    
    delete:
      summary: Remove the account entry in the database for the user.
      description: |
        Called when a user leaves operando. Their privacy preferences and
        policies are deleted from the database.
      tags:
        - Users
        - DELETE
      parameters:
        - $ref: '#/parameters/user-id'
      responses:
        '204':
          description: The document (account info) was successfully deleted from the database.
        '404':
          description: Error. No document exists to be deleted.
          