swagger: '2.0'
info:
  version: 0.0.1
  title: eu.operando.core.bda
  description: Operando's BDA interfaces for administration console

  termsOfService: 'http://www.operando.eu/terms/'
  
  contact:
    name: OPERANDO development
    url: 'http://www.operando.eu/support'
    email: support@operando.eu
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'

host: 'localhost:8080'
schemes:
  - http
  - https
basePath: /operando/bda
produces:
  - application/json
consumes:
  - application/json
paths:
  /ac/job/status:
    get:
      description: Allows to get the status of a job
      parameters:
        - name: requestHeader
          in: body
          description: Identification of the requesting end user
          schema:
            $ref: '#/definitions/RequestHeader'
          required: true
        - name: jobId
          in: query
          description: Identification of the job to get the status about
          type: string
          required: true
      responses:
        '200':
          description: Successful response
  /ac/job/info/load:
    get:
      description: It forces the information loading for a given job
      parameters:
        - name: requestHeader
          in: body
          description: Identification of the requesting end user
          schema:
            $ref: '#/definitions/RequestHeader'
          required: true
        - name: jobId
          in: query
          description: Identification of the job to get the status about
          type: string
          required: true
      responses:
        '200':
          description: Successful response
  /ac/job/info/update:
    get:
      description: >-
        It forces the information updating for a given job, it only load last
        updates
      parameters:
        - name: requestHeader
          in: body
          description: Identification of the requesting end user
          schema:
            $ref: '#/definitions/RequestHeader'
          required: true
        - name: jobId
          in: query
          description: Identification of the job to get the status about
          type: string
          required: true
      responses:
        '200':
          description: Successful response
  /ac/job/list:
    get:
      description: It returns the list of jobs available for that user
      parameters:
        - name: requestHeader
          in: body
          description: Identification of the requesting end user
          schema:
            $ref: '#/definitions/RequestHeader'
          required: true
        - name: jobId
          in: query
          description: Identification of the job to get the status about
          type: string
          required: true
      responses:
        '200':
          description: Successful response
  /ac/user/subscribed:
    get:
      description: It returns the list of jobs subscribed for that user
      parameters:
        - name: requestHeader
          in: body
          description: Identification of the requesting end user
          schema:
            $ref: '#/definitions/RequestHeader'
          required: true
        - name: jobId
          in: query
          description: Identification of the job to get the status about
          type: string
          required: true
      responses:
        '200':
          description: Successful response
  /ac/user/rights/execution:
    get:
      description: It returns the list of jobs subscribed for that user
      parameters:
        - name: requestHeader
          in: body
          description: Identification of the requesting end user
          schema:
            $ref: '#/definitions/RequestHeader'
          required: true
        - name: jobId
          in: query
          description: Identification of the job to get the status about
          type: string
          required: true
      responses:
        '200':
          description: Successful response
  /ac/user/rights/access:
    get:
      description: It returns the list of jobs subscribed for that user
      parameters:
        - name: requestHeader
          in: body
          description: Identification of the requesting end user
          schema:
            $ref: '#/definitions/RequestHeader'
          required: true
        - name: jobId
          in: query
          description: Identification of the job to get the status about
          type: string
          required: true
      responses:
        '200':
          description: Successful response
  /ac/event/change:
    get:
      description: It returns the list of jobs subscribed for that user
      parameters:
        - name: requestHeader
          in: body
          description: Identification of the requesting end user
          schema:
            $ref: '#/definitions/RequestHeader'
          required: true
        - name: jobId
          in: query
          description: Identification of the job to get the status about
          type: string
          required: true
      responses:
        '200':
          description: Successful response
  /ac/job/change:
    get:
      description: It returns the list of jobs subscribed for that user
      parameters:
        - name: requestHeader
          in: body
          description: Identification of the requesting end user
          schema:
            $ref: '#/definitions/RequestHeader'
          required: true
        - name: jobId
          in: query
          description: Identification of the job to get the status about
          type: string
          required: true
      responses:
        '200':
          description: Successful response
  /mc/osp/{osp_id}/jobs:
    get:
      description: Function that returns all the jobs avaliable to the requester detailing those suscribed
      tags:
        - Management Console
      parameters:
        - name: osp_id
          in: path
          description: The unqiue regulation ID for the new regulation created.
          required: true
          type: number
          format: integer
      responses:
        '200':
          description: the osp_id exists
          schema: 
            $ref: '#/definitions/OSPJobs'
        '404':
          description: the osp_id does not exist
  /mc/osp/{osp_id}/jobs/{job_id}/subscription:
    put:
      description: Function that allows to modify the subscription to a job
      tags:
        - Management Console
      parameters:
        - name: osp_id
          in: path
          description: The unique ID for the osp.
          required: true
          type: number
          format: integer
        - name: job_id
          in: path
          description: The unique ID for the job.
          required: true
          type: number
          format: integer
        - name: oSPJobsSubscriptionRequest
          in: body
          description: user to add to the system
          required: true
          schema: {
            "$ref": "#/definitions/OSPJobsSubscriptionRequest"
          }
      responses:
        '200':
          description: the job subscription added/modified
        '404':
          description: the osp_id or job_id does not exist
    get:
      description: Function that allows to modify the subscription to a job
      tags:
        - Management Console
      parameters:
        - name: osp_id
          in: path
          description: The unique ID for the osp.
          required: true
          type: number
          format: integer
        - name: job_id
          in: path
          description: The unique ID for the job.
          required: true
          type: number
          format: integer
      responses:
        '200':
          description: the job subscription 
          schema: 
            $ref: '#/definitions/OSPJobs'          
        '404':
          description: the osp_id or job_id does not exist
  /mc/job/subscribe:
    get:
      description: >-
        Allows to subscribe to a job for its execution. <br> <ul> <li>If no
        start date is specified it start inmediately. </li> <li>If no end date
        is specified it executes forever. </li> <li>If no periodicity is
        specified it executes just one time.  </li> </ul>
      parameters:
        - name: requestHeader
          in: body
          description: Identification of the requesting end user
          schema:
            $ref: '#/definitions/RequestHeader'
          required: true
        - name: jobId
          in: query
          description: Identification of the job to be subscribed
          type: string
          required: true
        - name: startDate
          in: query
          description: Identification of the job subscribtion starting date
          type: string
          format: date-time
        - name: endDate
          in: query
          description: Identification of the job subscribtion end date
          type: string
          format: date-time
        - name: period
          in: query
          description: >-
            Identification of job execution periodicity -> yearly, monthly,
            weekly, ...
          type: string
      responses:
        '200':
          description: Successful response
  /mc/job/unSubscribe:
    get:
      description: unSubscribe to a job for its execution. <br>
      parameters:
        - name: requestHeader
          in: body
          description: Identification of the requesting end user
          schema:
            $ref: '#/definitions/RequestHeader'
          required: true
        - name: jobId
          in: query
          description: Identification of the job to be unSubscribed
          type: string
          required: true
      responses:
        '200':
          description: Successful response
  /out/report/download:
    get:
      description: provides a link to download a report
      parameters:
        - name: requestHeader
          in: body
          description: Identification of the requesting end user
          schema:
            $ref: '#/definitions/RequestHeader'
          required: true
        - name: jobId
          in: query
          description: Identification of the job to get the status about
          type: string
          required: true
      responses:
        '200':
          description: Successful response
definitions:
  RequestHeader:
    type: object
    properties:
      requestId:
        type: string
      requesterId:
        type: string
      requesterComponentId:
        type: string
      proxyId:
        type: string
      requestDateTime:
        type: string
        format: date-time
    required:
      - requestId
      - requesterId
  BDAJob:
    type: object
    properties:
      jobId:
        type: integer
      jobName:
        type: string
      subscribed:
        type: boolean
      status:
        type: string
      downloadLink:
        type: string
  OSPJobs:
    type: object
    description: OSP job list
    properties:
      jobs: {
            "type": "array",
            "items": {
              "$ref": "#/definitions/BDAJob"
            }
      }
  OSPJobsSubscriptionRequest:
    type: object
    description: job subscription
    properties:
      subscribed:
        type: boolean
      frequency:
        type: string
