swagger: '2.0'
info:
  title: eu.operando.core.pfb
  description: Operando PfB module.
  version: "1.0.0"
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: localhost:8080
schemes:
- http
- https
produces:
- application/json
################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: Deals
    description: |
      Privacy for benefit products that have been accepted by a user
  - name: Offers
    description: |
      Privacy for benefit product, offered by an OSP to consumers
  - name: OSPs
    description: APIs related to management of Online Service Providers PfB accounts.
  - name: Users
    description: End users of the Privacy Service Provider.
################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  offer_id:
    name: offer_id
    in: path
    description: The offer identifier number
    type: string
    required: true
  deal_id:
    name: deal_id
    in: path
    description: The unique identifier number of a deal.
    type: string
    required: true
  user_id:
    name: user_id
    in: path
    description: The user identifier number
    type: string
    required: true
  osp_id:
    name: osp_id
    in: path
    description: The identifier number of an OSP
    type: string
    required: true
################################################################################
#                                   PATHs                                      #
################################################################################
paths:
  /operando/core/pfb/offers:
    post:
      summary: Creates a new offer for an OSP .
      description: Request from Administration Console to create a new offer for an OSP.
      operationId: createOffer
      tags:
        - Offers
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: offer
          in: body
          description: The offer data in JSON format.
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/eu.operando.definitions.pfb.yaml#/OfferRequest'
          required: true
      responses:
        "200":
          description: Successful operation
          schema:
            type: object
            properties:
              data:
                type: object
                items:
                  $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/eu.operando.definitions.pfb.yaml#/OfferStatus'
        default:
          description: Unexpected error
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Error.yaml'
  /operando/core/pfb/offers/search:
    get:
      summary: Search offers in databse
      description: Extension or management console send request to PfB service to get a list of offers by specific search terms (e.g Gets offers related to a website  when signup page is detected)
      tags:
        - Offers
      operationId: getOffers
      parameters:
        - name: website_url
          in: query
          description: URL of the website to get offers related to specific URL
          type: string
        - name: website_id
          in: query
          description: ID of the website to get offers related to specific website ID
          type: string
        - name: osp_id
          in: query
          description: ID of the OSP to list of all offers created by specific OSP..
          type: string
        - name: user_id
          in: query
          description: ID of the user to limit offers to those apllicable to specific user.
          type: string
      responses:
        "200":
          description: Successful operation
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/eu.operando.definitions.pfb.yaml#/Offer'
        default:
          description: Unexpected error
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Error.yaml'	
  /operando/core/pfb/offers/{offer_id}:
    parameters:
      - $ref: '#/parameters/offer_id'
    get:      
      summary: Gets the status of a given offer.
      description: Get the status of a given offer.
      tags:
        - Offers
      operationId: getOfferStatus
      produces:
        - application/json        
      responses:
        "200":
          description: Successful operation (the offer status)
          schema:
            type: object
            properties:
              data:
                $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/eu.operando.definitions.pfb.yaml#/OfferStatus'
        default:
          description: Unexpected error
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Error.yaml'
    put:
      summary: Update an offer for an OSP .
      description: Request from Administration Console to update existing offer. (limited to specific fields - TBD).
      tags:
        - Offers
      operationId: updateOffer
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: offer
          in: body
          description: The offer data in JSON format.
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/eu.operando.definitions.pfb.yaml#/OfferRequest'
          required: true
      responses:
        "200":
          description: Successful operation (the offer status)
          schema:
            type: object
            properties:
              data:
                $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/eu.operando.definitions.pfb.yaml#/OfferStatus'
        default:
          description: Unexpected error
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Error.yaml'
  /operando/core/pfb/deals:
    post:
      summary: Create a new deal. Indicates the user's acceptance for an offer.
      description: Triggered by the extension to PfB service to indicate that the user has chosen to accept the offer (i.e. initiated login with Social Network button)
      tags:
        - Deals
      operationId: createDeal
      produces:
        - application/json
      parameters:
        - name: deal
          in: body
          description: The deal data in JSON format.
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/eu.operando.definitions.pfb.yaml#/DealRequest'
          required: true
      responses:
        "200":
          description: Successful operation
          schema:
            type: object
            properties:
              data:
                $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/eu.operando.definitions.pfb.yaml#/Deal'
        default:
          description: Unexpected error
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Error.yaml'
  /operando/core/pfb/deals/{deal_id}:
    parameters:
      - $ref: '#/parameters/deal_id'
    get:      
      summary: Gets the status of a given deal.
      description: Get the status of a given deal.
      tags:
        - Deals
      produces:
        - application/json        
      responses:
        "200":
          description: Successful operation (the offer status)
          schema:
            type: object
            properties:
              data:
                $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/eu.operando.definitions.pfb.yaml#/Deal'
        default:
          description: Unexpected error
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Error.yaml'
    delete:
      summary: Cancel a deal.
      description: Request from Privacy Dashboard to cancel a deal. The deal is not deleted, but updated by setting the current date value to canceled_at field.
      tags:
        - Deals
      operationId: cancelDeal
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: Successful operation
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Error.yaml'   
  /operando/core/pfb/deals/{deal_id}/acknowledgement:
    parameters:
      - $ref: '#/parameters/deal_id'
    post:
      summary: Acknoledge a deal by OSP.
      description: This API call is used by the OSP to acknowledge a deal and approve that offer was awarded to user
      tags:
        - Deals
      operationId: offerAccepted
      produces:
        - application/json
      parameters:
      - in: query
        name: ospId
        description: Osp Id.
        required: true
        type: string
      - in: query
        name: offerId
        description: Offer Id.
        required: true
        type: string
      responses:
        "200":
          description: Successful operation
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Error.yaml'
  /operando/core/pfb/osps:
    post:
      summary: Registers a new OSP.
      description: Request from Administration Console to register a new Online Service Provider.
      tags:
        - OSPs
      operationId: registerOSP
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: osp
          in: body
          description: The OSP data in JSON format.
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/eu.operando.definitions.pfb.yaml#/OSPRequest'
          required: true
      responses:
        "200":
          description: Successful operation.
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Error.yaml'
  /operando/core/pfb/osps/{osp_id}/deals:
    parameters:
      - $ref: '#/parameters/osp_id'
    get:      
      summary: List of all users and their active deals for the OSP.
      description: Request from an OSP to get a list of all users and their active deals for specific OSP (could be also for report) .
      tags:
        - Deals
        - OSPs
      operationId: getAcceptedDealsByOSP
      produces:
        - application/json
      responses:
        "200":
          description: Successful operation (list of offers' ids associated with users' ids).
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/eu.operando.definitions.pfb.yaml#/OfferUser'
        default:
          description: Unexpected error
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Error.yaml'
  /operando/core/pfb/users/{user_id}/deals:
    parameters:
      - $ref: '#/parameters/user_id'
    get:      
      summary: Returns list of offers accepted by user.
      description: Request from privacy dashboard to get list of offers accepted by user (and acknowledged by OSP).
      tags:
        - Users
        - Deals
      operationId: getAcceptedDealsByUser
      produces:
        - application/json        
      parameters:
        - name: status
          in: body
          description: filter deals by category / status
          schema:
            type: string
            enum:
              - all
              - pending
              - accepted
              - rejected
      responses:
        "200":
          description: Successful operation (list of offers accepted by user).
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/eu.operando.definitions.pfb.yaml#/Deal'
        default:
          description: Unexpected error
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Error.yaml'