swagger: '2.0'
info:
  title: USER DEVICE ENFORCEMENT API
  description: User Device Enformcement API
  version: 0.2.0
  contact:
    email: raf@rms.ro
    name : RomSoft
    url: http://www.operando.eu/
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
schemes:
  - https
  - http
host: 'localhost:8080'
basePath: /operando/core/ude
produces:
  - application/json
################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: Privacy Settings
    description: |
      Privacy Settings intend to secure the user private data.
  #- name: OSE
  #  description: APIs related to Online Service Provider Enforcement.

################################################################################
#                                   Parameters                                 #
################################################################################        
parameters:
  user_id:
    name: user_id
    in: query
    description: Unique identifier representing a specific user
    type: string
    format: uuid
    required: true
  osp_id:
    name: osp_id
    in: query
    description: OSP unique identifier
    type: string
    required: true  
################################################################################
#                                   Paths                                      #    
################################################################################
paths:
  ################################################
  #            User Device Enforcement           #
  ################################################
  /privacy_settings:
    get:
      summary: Get Privacy Settings
      description: |
        The UDE endpoint returns the current privacy settings for all social
        networks. It is called by Watchdog when it requests to get current
        settings
      parameters:
        - $ref: '#/parameters/user_id'
        - $ref: '#/parameters/osp_id'
        # not 100% sure if we ask for an entire list to prevent a slow processing because of the many http requests
        #- name: osp_list
        #  in: body
        #  description: OSP_list
        #  schema:
        #    type: array
        #    items:
        #      $ref: '#/definitions/OSP'
        #  required: true    
      tags:
        - Privacy Settings
      responses:
        200:
          description: An array of privacy settings
          schema:
            type: array
            items:
              $ref: '#/definitions/PrivacySetting'
        404: 
          description: Not found or invalid
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      summary: Apply Privacy Settings
      description: Called by OSE when it wants to update user’s settings
      parameters:
        - $ref: '#/parameters/user_id'
        - $ref: '#/parameters/osp_id'
        - name: settings  
          in: body
          required: true
          description: An array containing the privacy settings that shoul be applied
          schema:
            type: array
            items: 
              $ref: '#/definitions/PrivacySetting'
      tags:
        - Privacy Settings
      responses:
        200:
          description: Privacy Setting were successfully applied
          schema:
            $ref: '#/definitions/Status'
        404:
          description: Not found or invalid. (e.g. user_id, osp_id)
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
################################################################################
#                              Objects Definitions                             #
################################################################################   
definitions:
  PrivacySetting:
    $ref: "https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/PrivacySetting.yaml"
  Status:
    $ref: "https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Status.yaml"
  Error:
    $ref: "https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Error.yaml"
