swagger: '2.0'
info:
  title: eu.operando.core.ldb
  description: Operando LogDB module.
  version: "1.0.0"
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: localhost:8080
schemes:
- http
- https
produces:
- application/json
################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: Log
    description: Inserts received data to the database by using Log4j.
  
################################################################################
#                                   Parameters                                 #
################################################################################

paths:
  /operando/core/ldb:
    post:
      summary: Inserts received data to the database.
      description: Inserts received data to the database by using Log4j.
      tags:
        - Log
      operationId: log
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - name: request
        in: body
        description: The request data in JSON format to be inserted in the database by using Log4j
        schema:
          $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/eu.operando.definitions.logdb.yaml#/LogRequest'
        required: true
      responses:
        "200":
          description: Successful operation
          schema:
            type: string
        default:
          description: Unexpected error
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Error.yaml'
  /operando/core/ldb/log:
    post:
      summary: Inserts received data to the database.
      description: Inserts received data to the database by using Log4j.
      tags:
        - Log
      operationId: logTicket
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - name: request
        in: body
        description: The request data in JSON format to be inserted in the database by using Log4j
        schema:
          $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/eu.operando.definitions.logdb.yaml#/LogRequestTicket'
        required: true
      responses:
        "200":
          description: |
            Succesful operation.
        '400':
          description: |
            The client inputs to the operation are incorrect or invalid. The caller should check the inputs are valid based upon the returned error message.
        '403':
          description: |
            Error. The service ticket failed to validate.
        '415':
          description: |
            The operation consumes json messages. Please, check that the sent message is in json format.
        