swagger: '2.0'
info:
  version: 1.0.0
  title: Policy Computation
  description: "Provides a set of functions that provide analysis and computation of privacy policies. The following describe the overall behaviours of the component\n\n1) Evaluate if a particular data request, or sequence of data requests from an OSP complies with the user's privacy policy; \n\n2) Evaluate if the behaviour of an OSP complies with the appropriate privacy regulations;\n\n3) Compute and manage the UPP of a user. Where a new user subscribes to the service, create the new UPP; where an existing user subscribes to a new service, or updates their privacy preferences recompute the UPP.\n"
  termsOfService: 'http://www.operando.eu/terms/'
  contact:
    name: IT Innovation
    url: 'http://www.operando.eu/support'
    email: support@operando.eu
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
schemes:
  - http
  - https
host: operando.eu
basePath: /policy_computation
tags:
  - name: Policy Evaluation
    description: |
      Evaluation of OSP behaviour against UPP policies.
  - name: Policy Compliance
    description: |
      Evaluation of OSP behaviour against privacy regulations.
  - name: Policy Compute
    description: Methods related to the computation of UPPs of a user.
  - name: Privacy Legislation
    description: |
      Management of privacy legislation.
paths:
  /evaluate_osp_request:
    post:
      summary: Evaluate a set of OSP requests against the User Privacy Policy
      description: |
        Called by the Rights Management Component when evaluating if an OSP
        request or set of requests matches the user preferences stored in the
        user's UPP.
      parameters:
        - name: user_id
          in: query
          description: Unique identifier representing a specific user
          type: string
          required: true
          format: uuid
        - name: osp_id
          in: query
          description: OSP unique identifier
          type: string
          required: true
        - name: osp_request
          in: body
          description: "The set of requests that the OSP wants to perform on a user's private data"
          schema:
            type: array
            items:
              $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/OSPDataRequest.yaml#/OSPDataRequest'
          required: true
      tags:
        - Policy Evaluation
        - POST
      responses:
        '200':
          description: |
            Evaluation was successful and a report is produced. The report indicates if the request(s) is allowed. Where not allowed, the report indicates.
          schema:
            $ref: '#/definitions/PolicyEvaluationReport'
  
  /evaluate_osp_policy:
    post:
      summary: Evaluate a set of OSP requests against the legislation
      description: |
        Method to run a new OSP registers with OPERANDO; or a legislation
        changes.
      parameters:
        - name: osp_id
          in: query
          description: OSP unique identifier
          type: string
          required: true
        - name: osp_request
          in: body
          description: "The set of requests that the OSP will carry out on a user's private data"
          schema:
            type: object
            items:
              $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/OSPPrivacyPolicy.yaml#/OSPPrivacyPolicy'
          required: true
      tags:
        - Policy Compliance
        - POST
      responses:
        '200':
          description: 'Compliance was successful and a report is produced. The report indicates if the request(s) complies with legislation. Where there is a breach, the report indicates the reason for the breach.'
          schema:
            $ref: '#/definitions/PolicyEvaluationReport'
            
  /compute_user_privacy_policy:
    post:
      summary: Creates or changes the UPP based on a user subscribing to a new service (enters OSP_ID in query) or simply enters their preferences.
      description: |
        Called by the management console when a user subscribes to a new OSP or enters their prefs.
      parameters:
        - name: osp_id
          in: query
          description: OSP unique identifier of the OSP to compute and add to the UPP
          type: string
          required: false
        - name: user_id
          in: query
          description: user unique identifier of the UPP to compute
          type: string
          required: true
        - name: osp_request
          in: body
          description: |
            The set of requests that the OSP will carry out on a user's private data. This will likely be stored in the DB, so not needed to pass each time.
          schema:
            type: array
            items:
              $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/UserPreference.yaml#/UserPreference'
          required: false
      tags:
        - Policy Compute
        - POST
      responses:
        '200':
          description: 'UPP update was successful and a report is produced. The report indicates if the request(s) complies matches the subscription. Where there is a mismatch, the report indicates the reason for the mismatch.'
          schema:
            $ref: '#/definitions/PolicyEvaluationReport'
  
            
  /regulations/{reg_id}/:
    post:
      description: | Called by the Regulator API after a  
        new regulation is entered into OPERANDO. The regulation is first created and stored by the policy DB. Existing UPPs 
        are then evaluated to see if they comply with the regulation.
      tags:
        - Privacy Legislation
      parameters:
        - name: reg_id
          in: path
          description: The unqiue regulation ID for the new regulation created.
          required: true
          type: number
          format: integer32
        - name: regulation
          in: body
          description: The description of the new regulation.
          required: true
          schema:
            type: array
            items:
              $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/PrivacyRegulation.yaml#/PrivacyRegulation'
      responses:
        '200':
          description: Successful response. The regulation has been added.
        '409':
          description: 'Error occured. The resource already exists, so a new resource cannot be created.'
    
    put:
      description: |
        Called by the Regulator API. An updated regulation is entered into
        OPERANDO. The regulation is stored in the policy DB. Existing UPPs are
        then evaluated to see if they comply with the regulation.


        Pre-condition -- The regulation must have been written to the system.
      tags:
        - Privacy Legislation
        - PUT
      parameters:
        - name: reg_id
          in: path
          description: The unqiue regulation ID for the changed regulation.
          required: true
          type: number
          format: integer32
        - name: regulation
          in: body
          description: The description of the changed regulation.
          required: true
          schema:
            type: array
            items:
              $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/PrivacyRegulation.yaml#/PrivacyRegulation'
      responses:
        '200':
          description: Successful response. The regulation has been added.
        '404':
          description: Error. The resource does not exist to be updated.

definitions:
  PolicyEvaluationReport:
    type: object
    properties:
      status:
        type: string
        description: Request status success or error
      compliance:
        type: string
        description: Message stating the reasons any request failed e.g. breaks the user's privacy preferences.

