swagger: '2.0'
info:
  title: Browser Extension API
  description: Browser Extension  API
  version: 0.2.0
  contact:
    email: raf@rms.ro
    name : RomSoft
    url: http://www.operando.eu/
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
schemes:
  - https
  - http
basePath: /operando/browser-extension  
host: 'localhost:8080'
produces:
  - application/json
################################################################################
#                                      Tags                                    #
################################################################################  
tags: 
  - name: Browser Identity
    description: Browser Identity APIs. 
  - name: Social Networks
    description: Social Networks Privacy & Security APIs
  - name: Browser Apps & Extensions
    description: Browser Apps & Extensions Privacy & Security APIs  

################################################################################
#                                   Parameters                                 #
################################################################################ 
parameters:
  user_id:
    name: user_id
    in: path
    description: User's unique identifier
    type: string
    required: true
    format: uuid
  social_network:
    name: social_network
    in: query
    description: Social Network Name
    type: string
    required: true      
  url:
    name: url
    in: query
    description: Social Network URL
    type: string
    required: true     
  application_id:  
    name: application_id
    in: path
    description: Application unique identifier
    type: string
    required: true  
  reason:
    name: reason
    in: body
    required: true
    description: Reason for this action
    schema:
      $ref: '#/definitions/Reason'
################################################################################
#                                     Paths                                    #
################################################################################    
paths:
  /social_networks/{user_id}:
    get:
      summary: Ask for all user's social networks  
      parameters :
        - $ref: "#/parameters/user_id"
      tags:
        - Social Networks
      responses:
        200:
          description: An array containing user social networks
          schema:
            type: array
            items:
              $ref: '#/definitions/SocialNetwork'
        404:
          description: Identity not found
          schema: 
            $ref: '#/definitions/Status'
        500:
          description: Unexpected error
          schema: 
            $ref: '#/definitions/Error'  
  /social_networks/settings/{user_id}:
    get:
      summary: Ask for all user's social networks  
      parameters :
        - $ref: "#/parameters/user_id"
        - $ref: "#/parameters/social_network"
        - $ref: "#/parameters/url"
      tags:
        - Social Networks
      responses:
        200:
          description: An object containing social network settings
          schema:
            type: array
            items:
              $ref: '#/definitions/PrivacySetting'
        404:
          description: User_id not found
          schema: 
            $ref: '#/definitions/Status'        
        500:
          description: Unexpected error
          schema: 
            $ref: '#/definitions/Error'
    patch: 
      summary: Apply secure settings for the social network
      parameters :
        - $ref: "#/parameters/user_id"
        - $ref: "#/parameters/social_network"
        - $ref: "#/parameters/url"
        - name: privacy_settings
          in: body
          schema:
            type: array
            items:
              $ref: '#/definitions/PrivacySetting'
          description: An array containing Privacy settings
      tags:
        - Social Networks
      responses:
        200: 
          description: An object containing a successfully status
          schema:
            $ref: '#/definitions/Status'
        404:
          description: User_id not found
          schema: 
            $ref: '#/definitions/Status'    
        500:
          description: Unexpected error
          schema: 
            $ref: '#/definitions/Error'
  /apps/{user_id}:
    get:
      summary: Get all installed apps, extension and themes
      parameters: 
        - $ref: "#/parameters/user_id"
        - name: type
          in: query
          description: App type (extension, application, theme)
          type: string
      tags:
        - Browser Apps & Extensions
      responses:
        200: 
          description: An array containing all installed apps, extensions and themes
          schema:
            type: array
            items: 
              $ref: '#/definitions/Application'
        404:
          description: User_id not found
          schema: 
            $ref: '#/definitions/Status'    
        500:
          description: Unexpected error
          schema: 
            $ref: '#/definitions/Error'        
  /apps/disable/{user_id}/{application_id}:
    put:
      summary: Suggest to extension to disable an application presenting the reason for the action
      parameters:
        - $ref: "#/parameters/user_id"
        - $ref: "#/parameters/application_id"
        - $ref: "#/parameters/reason"
      tags:
        - Browser Apps & Extensions
      responses: 
        200:
          description: Successfully request
          schema:
            $ref: '#/definitions/Status'
        404:
          description: User_id not found
          schema: 
            $ref: '#/definitions/Status'     
        500:
          description: Unexpected error
          schema: 
            $ref: '#/definitions/Error'    
  /apps/{user_id}/{application_id}:
    delete:
      summary: Suggest to extension to uninstall an application presenting the reason for the action
      parameters:
        - $ref: "#/parameters/user_id"
        - $ref: "#/parameters/application_id"
        - $ref: "#/parameters/reason"
      tags:
        - Browser Apps & Extensions
      responses: 
        200:
          description: Successfully request
          schema:
            $ref: '#/definitions/Status'
        500:
          description: Unexpected error
          schema: 
            $ref: '#/definitions/Error'            

definitions:
  SocialNetwork:
    $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/SocialNetwork.yaml'
  PrivacySetting:
    $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/SNPrivacySetting.yaml'
  Application:
   $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Application.yaml'    
  Reason: 
    $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Reason.yaml'
  Status:
    $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Status.yaml'
  Error:
    $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Error.yaml'
