
swagger: '2.0'

info:
  version: "0.0.9"
  title: OSP Enforcement (OSE)

  description: |
    
    The OSP enforcement component provides a set of functions that manage the interaction of OSP behaviour with the user's private data. The OSE component is largely in charge of ensuring that an OSP follows both privacy regulations and policies put in place by the user (i.e. in the OPERANDO UPPs). There are a set of events that trigger the usage of this API.
    
    1) When a new G2C OSP registers with OPERANDO via the OPERANDO console. The management console informs the OSE, which then checks that an OSP conforms with existing privacy regulations; if it breaches the regulations, the OSE returns via the management console a report describing the breaches.
    
    2) When a change of OSP privacy policy or of the OSP's privacy settings are detected by the watchdog component. The
    watchdog component sends a message to a privacy analyst who reviews any changes. The privacy analyst may then
    inform the OSE of the new OSP information (to be checked for compliance with regulations and users' UPPs.
    
    3) When a privacy legislation is entered (or changed) via the Regulator API. The OSE checks registered OSPs for compliance with the new regulations; where there is a breach the OSP is notified either by e-mail or the console.

  termsOfService: http://www.operando.eu/terms/
  contact:
    name: IT Innovation
    url: http://www.operando.eu/support
    email: support@operando.eu
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
    
schemes:
  - http
  - https
  
host: operando.eu

basePath: /

################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: Privacy Settings
    description: |
      API related to the management of a user's OSP privacy settings
  - name: Privacy Legislation
    description: |
      Management of privacy legislation.
  - name: Privacy Policy
    description: APIs related to management of OSP privacy policies and behaviour.

################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
  user-id:
    name: user-id
    in: query
    description: The user identifier number
    type: string
    required: true
  osp-id:
    name: osp-id
    in: path
    description: The identifier number of an OSP
    type: string
    required: true 
  reg-id:
    name: reg-id
    in: path
    description: The identifier number of a regulation
    type: string
    required: true

################################################################################
#                                   Paths                                      #
################################################################################

paths:
          
  /osps/{osp-id}/privacy_settings/:
    get:
      description: |
        Simple retrieval of an OPERANDO registered OSP's privacy settings.
        This method is called by the watchdog component when it requests the settings last applied by the OSE component.
        
        Pre condition -- An OPERANDO user must have registered with the OPERANDO platform and subscribed to the OSP service in question.
        
        Pre condition --The user's UPP must be stored in the Policy DB component and contain the privacy settings for the OSP service in question.
        
        When the query includes a user id; that user's settings are returned. For a request with no user id as a query parameter, the operation returns the general set of settings covered by this OSP.
        
      tags:
        - Privacy Settings
      parameters:
        - $ref: '#/parameters/osp-id'
        - $ref: '#/parameters/user-id'

      responses:
        200:
          description: Successful response. The privacy settings information for this user at the given OSP is returned.
          schema:
            title: ArrayOfPrivacySettings    
            type: array
            items:
              $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/PrivacySetting.yaml'
              
        404: 
          description: Error response. The settings resource does not exist. Or the OSP does not exist. Or the user is not subscribed to the OSP in OPERANDO.

    put:
      description: |
        Called when a change in privacy settings is detected at a specific OSP. The OSE evaluates the impact of the changed settings and computes the required new settings and ensures that they are enforced at the OSP and the new settings stored in the policy DB.
      tags:
        - Privacy Settings

      parameters:
        - $ref: '#/parameters/osp-id'
        - $ref: '#/parameters/user-id'
        
        - name: osp_settings
          in: body
          description: The set of settings that have now changed. This is the complete OSP settings list to be compared with the existing stored settings for this OSP for the user.
          schema:
            title: ArrayOfPrivacySettings    
            type: array
            items:
              $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/PrivacySetting.yaml'
          required: true
          
      responses:
        200:
          description: Successful response. The privacy settings have been agreed and applied via the OSE and the browser extension software. Note, the response here only needs to indicate that the method worked not whether the settings have been applied in practice.
        404: 
          description: Error response. The user does not exist. Or the OSP does not exist. Or the user is not subscribed to the OSP in OPERANDO.
          

  /osps/{osp-id}/:         
    put:
      description: |
        Called when a change in an OSP's privacy policy detected by OPERANDO (or a new OSP is registered). OSE computes whether the OSP policy complies with regulations; complies with UPP. It updates UPPs where appropriate and notifies users and OSP if there are issues with the updated privacy policy.
          
        Pre-condition -- The OSP must be registered with OPERANDO and it must have an existing policy stored in the policy DB.
          
      tags:
        - Privacy Policy
        
      parameters:
        - $ref: '#/parameters/osp-id'
            
        - name: osp_policy
          in: body
          description: The set of individual policies that have now compose the OSP's new privacy policy. This is the complete OSP list of the policies to be compared with the existing stored policy for this OSP.
          required: true
          schema:
              $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/OSPPrivacyPolicy.yaml#/OSPPrivacyPolicy'

      responses:
        200:
          description: Successful response. The privacy policy has been received and being processed. Information will be sent via other operation sequences.
        404: 
          description: Error response. The OSP does not exist. It has not been registered with OPERANDO.

  /osps/{osp-id}/privacytext/: 
    put:
      description: |
          Notify the OSE of a change in policy text

      tags:
          - Privacy Policy
          
      parameters:
        - $ref: '#/parameters/osp-id'
            
        - name: osp_privacy_text
          in: query
          description: The complete privacy policy text of the OSP.
          required: true
          type: string
        
      responses:
          # Response code
        204:
          description: Successful response, The privacy text update analysis has begun.
        409:
          description: Error occured. The resource already exists, so a new resource cannot be created.
  
  /osps/{osp-id}/workflows/: 
    put:
      description: |
          Notify the OSE of a change in an OSP's workflow

      tags:
          - Privacy Policy
          
      parameters:
        - $ref: '#/parameters/osp-id'
            
        - name: osp_workflow
          in: body
          description: The workflow changes of the OSP.
          required: true
          schema:
            $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/OSPDataRequest.yaml#/OSPDataRequest'
              
      responses:
          # Response code
        204:
          description: Successful response, The workflow update analysis has begun.
        409:
          description: Error occured. The resource already exists, so a new resource cannot be created.
              
  /regulations/: 
    post:
      description: |
        Called by the Regulator API. A New regulation is entered into OPERANDO. Existing OSPs are then evaluated to see if they comply with the regulation. If not they are sent a report about how to comply.
      
      tags:
         - Privacy Legislation
          
      parameters:   
        - name: regulation
          in: body
          description: The description of the new regulation.
          required: true
          schema:
              $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/PrivacyRegulation.yaml#/PrivacyRegulation'
              
      responses:
             # Response code
        201:
          description: Successful response. The regulation has been created.
        409:
          description: Error occured. The resource already exists, so a new resource cannot be created.
        
  /regulations/{reg-id}/:             
    put:
      description: |
        Called by the Regulator API. A change to a regulation is entered into OPERANDO. Existing OSPs are then evaluated to see if they comply with the regulation. If not they are sent a report about how to comply.
          
          Pre-condition -- The regulation must have been written to the system.
          
      tags:
        - Privacy Legislation
          
      parameters:
        - $ref: '#/parameters/reg-id'
          
        - name: regulation
          in: body
          description: The description of the changed regulation.
          required: true
          schema:
              $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/PrivacyRegulationInput.yaml#/PrivacyRegulationInput'

      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response. The regulation has been added.
        404:
          description: Error. The resource does not exist to be updated.
              
  /consent/{osp-id}/:
    get:
      description: |
        Retrieve the consent report for an OSP. This is the list of users subscribed
        to this OSP, and the consents they have given for this service to access
        their personal data.
    
      parameters:
      - $ref: '#/parameters/osp-id'
        
      responses:
        200:
          description: Successful response. The consent report is returned.
          schema:
            title: Consent Report    
            type: array
            items:
              $ref: '#/definitions/UserConsents'
              
        404: 
          description: Error response. The OSP does not exist, and a consent report is not available.

definitions:
  UserConsents:
    type: object
    description: |
        A list of consents provided by a user to the OSP.
    properties:
        userid: 
            type: string
            description: | 
                The unique ID of the OSP user is subscribed to and these consent policies concern. 

        consents:
            type: array
            description: Access policies.
            items:
              $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/AccessPolicy.yaml#/AccessPolicy'