swagger: '2.0'
info:
  title: OSP API
  description: API specification for OPERANDO's OSP API
  version: "0.0.2"
host: localhost
schemes:
  - https
basePath: /osp
produces:
  - application/json
################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
    
  report-id:
    name: report_id
    in: path
    description: the unique identifier of a report.
    type: string
    required: true
    
  report-format:
    name: format
    in: query
    description: the requested format of the report (e.g. pdf, html).
    type: string
    required: true
    
  service-ticket:
    $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/parameters/service-ticket.yaml'

################################################################################
#                                 Responses                                    #
################################################################################
responses:
  unauthorised:
    description: The user is not authenticated with the OPERANDO system. Check that the service ticket provided by the authentication service is correctly included in the message body.
  invalid:
    description: The request was invalid, e.g. an invalid document format.
  not-found:
    description: The report with the requested report id could not be found

################################################################################
#                                   Paths                                      #
################################################################################
paths:
  /bda/reports:
    get:
      description:   
         provides a link to download a report
      tags:
        - big data
      parameters:
        - $ref: '#/parameters/service-ticket'
        -
          name: jobId 
          in: query
          description: Identification of the job to get the status about
          type: string
          required: true
      responses:
        200:
          description: Successful response
          # PENDING what happens in case of failure???
        400:
          $ref: '#/responses/invalid'
        401:
          $ref: '#/responses/unauthorised'
        404:
          $ref: '#/responses/not-found'
  
  /reports/{report_id}:
    get:
      summary: Get a report.
      description: |
        Called by a regulator to obtain a report matching the given ID. Intended (at the moment) to return a compliance report relating to an OSP.
      tags:
        - reports
      parameters:
        - $ref: '#/parameters/service-ticket'
        - $ref: '#/parameters/report-id'
        - $ref: '#/parameters/report-format'
      responses:
        200:
          description: The request was successful. The report is returned in the response body in the requested format.
          schema:
            type: string
        400:
          $ref: '#/responses/invalid'
        401:
          $ref: '#/responses/unauthorised'
        404:
          $ref: '#/responses/not-found'
          