swagger: '2.0'
info:
  title: OSP API
  description: API specification for OPERANDO's OSP API
  version: "0.0.1"
host: localhost
schemes:
  - https
basePath: /osp
produces:
  - application/json
################################################################################
#                                   Parameters                                 #
################################################################################
parameters:
    
  report-id:
    name: report_id
    in: path
    description: the unique identifier of a report.
    type: string
    required: true
    
  report-format:
    name: format
    in: query
    description: the requested format of the report (e.g. pdf, html).
    type: string
    required: true
    
  service-ticket:
    $ref: 'https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/parameters/service-ticket.yaml'

################################################################################
#                                 Responses                                    #
################################################################################
responses:
  unauthorised:
    description: The user is not authenticated with the OPERANDO system. Check that the service ticket provided by the authentication service is correctly included in the message body.
  forbidden:
    description: The user is authenticated with the OPERANDO system, but is not allowed to perform the requested action.

################################################################################
#                                   Paths                                      #
################################################################################
paths:
  /bda/reports:
    get:
      description:   
         provides a link to download a report
      tags:
        - big data
      parameters:
        - $ref: '#/parameters/service-ticket'
        -
          name: requestHeader # ACTION REQUIRED TO AGREE ON THIS IN THE PROJECT, MAYBE WE NEED SOMETHING SUCH AS REQUESTINFO OR REQUEST HEADER
          in: body
          description: Identification of the requesting end user
          schema:
            $ref: '#/definitions/requestHeader'
          required: true
        -
          name: jobId 
          in: query
          description: Identification of the job to get the status about
          type: string
          required: true
      responses:
        200:
          description: Successful response
          # PENDING what happens in case of failure???
        401:
          $ref: '#/responses/unauthorised'
        403:
          $ref: '#/responses/forbidden'
  
  /reports/{report_id}:
    get:
      summary: Get a report.
      description: |
        Called by a regulator to obtain a report matching the given ID. Intended (at the moment) to return a compliance report relating to an OSP.
      tags:
        - reports
      parameters:
        - $ref: '#/parameters/service-ticket'
        - $ref: '#/parameters/report-id'
        - $ref: '#/parameters/report-format'
      responses:
        200:
          description: The request was successful. The report is returned in the response body in the requested format.
          schema:
            type: string
        401:
          $ref: '#/responses/unauthorised'
        403:
          $ref: '#/responses/forbidden'
          
################################################################################
#                              Object Definitions                             #
################################################################################   
definitions:
  requestHeader:
    type: object
    properties:
      requestId:
        type: string
      requesterId:
        type: string
      requesterComponentId:
        type: string
      proxyId:
        type: string
      requestDateTime:
        type: string
        format: date-time
    required:
    - requestId
    - requesterId