swagger: '2.0'
info:
  title: EMAIL SERVICES API
  contact:
    email: raf@rms.ro
    name : RomSoft
    url: http://www.operando.eu/
  description: Email Services API
  version: 0.4.0
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
schemes:
  - https
  - http
host: 'localhost:8080'
basePath: /operando/interfaces/email_services
produces:
  - application/json

################################################################################
#                                   Tags                                       #
################################################################################
tags: 
  - name: SendEmail
    description: Send email APIs. Those APIs are used for email forwarding service.
  - name: EmailNotification
    description: Email notifications for internal/external users
  - name: Identities Manager    
    description: APIs related to Identiy Management.
################################################################################
#                                   Parameters                                 #
################################################################################    

parameters:
  user_id:
    name: user_id
    in: path
    description: Unique identifier representing a specific user
    type: string
    format: uuid
    required: true
  email:
    name: email
    in: body
    description: Email Object that is forwarded by EmailService
    required: true
    schema:
       $ref: '#/definitions/Email'
  email_notification:
    name: email_notification
    in: body
    description: EmailNotification Object
    required: true
    schema:
       $ref: '#/definitions/EmailNotification'
  identity_id:
    name: identity_id
    in: path
    description: Unique identifier representing a specific identity
    type: string
    format: uuid
    required: true 

################################################################################
#                                   Paths                                      #
################################################################################

paths:
  ################################################
  #               Email Services                 #
  ################################################
  /email:
    post:
      summary: Interface used to send an email
      parameters:
        - $ref: '#/parameters/email'
      tags:
        - SendEmail
      responses:
        200:
          description: Request was successfully completed
          schema:
              $ref: '#/definitions/Status'
        420:       
          description: Timeout connection problem
          schema:
            $ref: '#/definitions/Status'
        500:
          description: Invalid command
          schema:
            $ref: '#/definitions/Error'
          
        501:
          description: Invalid parameters args
          schema:
            $ref: '#/definitions/Error'
        523:
          description: The total size of your mailing exceeds the recipient server's limits.
          schema: 
            $ref: '#/definitions/Error'

  ################################################
  #           Email Notifications                #
  ################################################            
            
  /email_notification:
    post:
      description: Emit email notifications to internal/external users
      parameters: 
        - $ref: '#/parameters/email_notification'
      responses:
        200:
          description: Request was successfully completed
          schema:
              $ref: '#/definitions/Status'
        500:
          description: Invalid command
          schema:
            $ref: '#/definitions/Error'
        501:
          description: Invalid parameters args
          schema:
            $ref: '#/definitions/Error'
        523:
          description: The total size of your mailing exceeds the recipient server's limits.
          schema: 
            $ref: '#/definitions/Error'      
              
  
  ################################################
  #               Identity Manager               #
  ################################################ 
  /identities/{user_id}:
    post:
      summary: Generate a new identity for an user
      parameters:
        - $ref: '#/parameters/user_id'
      tags:
        - Identities Manager
      responses:
        201:
          description: Get the created identiy object
          schema:
            $ref: '#/definitions/Identity'
        500:
          description: Unexpected error
          schema: 
            $ref: '#/definitions/Error'
    get:
      summary: Get user identities
      parameters: 
      - name: user_id
        in: path
        description: Unique identifier representing a specific user
        type: string
        format: uuid
        required: true
      tags:
        - Identities Manager    
      responses:
        200:
          description: Get all user identities
          schema:
            type: array
            items:
              $ref: '#/definitions/Identity'  
        404:
          description: Identites not found for this user
          schema: 
            $ref: '#/definitions/Status'
          
        500:
          description: Unexpected error
          schema: 
            $ref: '#/definitions/Error'              
  
  /identities/{user_id}/{identity_id}:
    delete:
      summary: Remove a certain identity
      parameters:
        - $ref: '#/parameters/user_id'
        - $ref: '#/parameters/identity_id'
      tags:
        - Identities Manager    
      responses:
        200:
          description: Identity successfully removed from system
          schema: 
            $ref: '#/definitions/Status'
        404:
          description: Identity not found
          schema: 
            $ref: '#/definitions/Status'
        500:
          description: Unexpected error
          schema: 
            $ref: '#/definitions/Error'
 
################################################################################
#                              Objects Definitions                             #
################################################################################        
definitions:
  EmailNotification:
    $ref : "https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/EmailNotification.yaml"
  Email:
    $ref : "https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Email.yaml"
  Identity:
    $ref : "https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Identity.yaml"
  Status:
    $ref : "https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Status.yaml"
  Error:
    $ref : "https://raw.githubusercontent.com/OPERANDOH2020/op-api-doc/master/definitions/Error.yaml"
